### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Felli** [Demynnfire/Flatty-esoTalk-Skin#1]
After uploading to my server, the skin doesn't work, any more information to help fix this?
![screenshot_1](https://cloud.githubusercontent.com/assets/2011633/5791272/420f2d6e-9e98-11e4-81ab-39ae9f821c81.png)

**Comment by Demynnfire** [comment]
I'm well aware of the problem; sadly there's nothing to do at this point, it needs a whole rework. The code is borken to the point that it'd only be usable on my long lost- highly modified version of esoTalk.
Sorry I couldn't help, I'll work start working on it and roll out a proper fix for it as soon as possible.
And thank you for your report, it's appreciated!
