### ISSUE TITLE
Scrolling Break

### ISSUE THREAD

**Issue by Felli** [Demynnfire/Flatty-esoTalk-Skin#3]
I'm having another problem that you might be able to help me with, scrolling seems to break the post and sidebar, any advice on how to fix this would be appreciated.
![http---makeagif com--media-1-18-2015-4pnqcd](https://cloud.githubusercontent.com/assets/2011633/5796072/a666c6a8-9f6c-11e4-953f-078a39536930.gif)

**Comment by Demynnfire** [comment]
As far as I see, it's a problem with browser/screen height. I was able to reproduce the error and will do some editing to fix it. Thank you for reporting again :)
